import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const figtree = Figtree({
  // variable: "--font-figtree",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${figtree.className} min-h-screen bg-blue700 flex justify-center px-4`}
      >
        <div className="max-w-md w-full h-full">{children}</div>
      </body>
    </html>
  );
}
