import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/user.context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const figtree = Figtree({
  // variable: "--font-figtree",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${figtree.className} dark`}>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
